# Generated by Django 5.2.4 on 2025-08-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('pending', 'Pending')], default='available', max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
