# Generated by Django 5.2.4 on 2025-08-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='house',
            name='hoa_fee',
        ),
        migrations.RemoveField(
            model_name='house',
            name='property_tax',
        ),
        migrations.RemoveField(
            model_name='house',
            name='square_feet',
        ),
        migrations.AlterField(
            model_name='house',
            name='bathrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='house',
            name='bedrooms',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='house',
            name='lot_size',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='houses/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('commercial', 'Commercial'), ('land', 'Land')], default='apartment', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='year_built',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
